'''
Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''
def triangulo(n):
	return n*(n+1)/2

def pentagono(n):
	return n*(3*n-1)/2

def hexagono(n):
	return float(n*(2*n-1))

maior_t = 0
maior_p = 0
maior_h = 0

for x in range(1,30000):
	t = triangulo(x)
	i = 1
	while pentagono(i) <= t:
		p = pentagono(i)
		if p == t:
			if x > maior_t: maior_t = x
			if i > maior_p: maior_p = i
		i += 1

'''
	for i in range(1,round(t)):
		p = pentagono(i)
		if p == t:
			if x > maior_t: maior_t = x
			if i > maior_p: maior_p = i
'''
print(maior_t, maior_p, maior_h)

'''
for x in range(1,300):
	triangulos.append(triangulo(x))
	pentagonos.append(pentagono(x))
	hexagonos.append(hexagono(x))
'''