# -*- coding: utf-8 -*-
'''
Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''
def triangulo(n):
	return n*(n+1)/2

def pentagono(n):
	return n*(3*n-1)/2

def hexagono(n):
	return float(n*(2*n-1))

lst_triangulos = []
lst_pentagonos = []
lst_hexagonos = []

maior_t = 0
maior_p = 0
maior_h = 0

inicio_t = 285
inicio_p = 165
inicio_h = 143

for x in range(inicio_t, inicio_t+15):
	lst_triangulos.append(triangulo(x))

for x in range(inicio_p, inicio_p+10):
	lst_pentagonos.append(pentagono(x))

for x in range(inicio_h, inicio_h+5):
	lst_hexagonos.append(hexagono(x))

print(lst_triangulos)
print(lst_pentagonos)
print(lst_hexagonos)